### PR TITLE
add my item

### PR DESCRIPTION
**Pull request by yoshinobu-fukumitsu**
student ID number: 2211255

please merge my pull request

### CODE REVIEW

**Comment by hajimu** [comment]
@yoshinobu-fukumitsu Unfortunately, somebody else's merge is now conflicting with yours. Please try again.

**Comment by yoshinobu-fukumitsu** [comment]
I resolve conflict

**Comment by hajimu** [comment]
@yoshinobu-fukumitsu Unlucky but you had bad timing :(
Another merge has arleady submitted before yours. Please try again.

**Comment by yoshinobu-fukumitsu** [comment]
I resolve again!

**Pull request merged**
