### PR TITLE
Hi, this PR is a assignment of ssd2022

### PR DESCRIPTION
**Pull request by tomoyasuzuki**
Add the new line at the bottom of README.md.

### CODE REVIEW

**Comment by hajimu** [comment]
Sorry but your branch now conflicts with others. Please resolve that. #Do not delete other's lines,

**Comment by hajimu** [comment]
Umm. Someone else already has made another update and that conflicts with yours again.

**Comment by hajimu** [comment]
@tomoyasuzuki please try again

**Comment by hajimu** [comment]
@tomoyasuzuki are you still there?

**Comment by tomoyasuzuki** [comment]
@hajimu 
Thank you.
I will try it today.

**Comment by tomoyasuzuki** [comment]
@tomoyasuzuki 
I Fixed conflicts.

**Pull request merged**
